export default async function handler(req, res) {
  // CORS headers for Capacitor (Mobile) and Localhost (Dev)
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");

  // Handle preflight OPTIONS request
  if (req.method === "OPTIONS") {
    return res.status(200).end();
  }

  // Only allow POST
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const { prompt } = req.body;

  if (!prompt) {
    return res.status(400).json({ error: "Prompt is required" });
  }

  const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY;
  const MODEL = "google/gemma-3n-e4b-it:free";
  const API_URL = "https://openrouter.ai/api/v1/chat/completions";

  if (!OPENROUTER_API_KEY) {
    return res.status(500).json({ error: "Server configuration error" });
  }

  try {
    const response = await fetch(API_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${OPENROUTER_API_KEY}`,
      },
      body: JSON.stringify({
        model: MODEL,
        messages: [{ role: "user", content: prompt }],
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error("OpenRouter Error:", errorText);
      return res
        .status(response.status)
        .json({ error: `Failed to fetch from AI model: ${errorText}` });
    }

    const data = await response.json();

    // Check if choices array exists and has length
    if (!data.choices || data.choices.length === 0) {
      console.error("No choices returned from AI:", data);
      return res
        .status(500)
        .json({ error: "No response text generated by AI model" });
    }

    const text = data.choices[0].message.content;

    if (!text) {
      return res.status(500).json({ error: "No text received from AI" });
    }

    // Return the raw text back to the client.
    // The client will handle extracting the JSON.
    return res.status(200).json({ result: text });
  } catch (error) {
    console.error("Server Error:", error);
    return res
      .status(500)
      .json({ error: `Internal server error: ${error.message}` });
  }
}
