export const config = {
  runtime: "edge",
};

// CORS headers for Capacitor (Mobile) and Localhost (Dev)
const headers = {
  "Access-Control-Allow-Origin": "https://fit-gen-three.vercel.app",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type",
};

/**
 * Creates a standard JSON Response object with the appropriate CORS headers.
 * @param {any} body - The data to be sent in the response body (will be stringified).
 * @param {number} status - The HTTP status code (e.g., 200, 400, 500).
 * @returns {Response} A standard Web API Response object.
 */
function createJsonResponse(body, status) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...headers, "Content-Type": "application/json" },
  });
}

/**
 * Verifies a Firebase ID token using the Firebase Auth REST API.
 */
async function verifyFirebaseToken(token) {
  const apiKey = process.env.VITE_FIREBASE_API_KEY;
  if (!apiKey)
    throw new Error("Server configuration error: Missing Firebase API key");

  const response = await fetch(
    `https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=${apiKey}`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ idToken: token }),
    }
  );

  if (!response.ok) {
    return false;
  }

  const data = await response.json();
  // If we get user data back, the token is valid
  return data.users && data.users.length > 0;
}

/**
 * Handles the actual communication with the OpenRouter AI model.
 *
 * @param {string} prompt - The user's input prompt for the AI.
 * @returns {Promise<string>} The generated text response from the AI.
 * @throws {Error} If the API key is missing, the fetch fails, or the response is invalid.
 */
async function fetchAIResponse(prompt) {
  const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY;
  const MODEL = process.env.MODEL;
  const API_URL = process.env.API_URL;

  if (!OPENROUTER_API_KEY) {
    throw new Error("Server configuration error: Missing API key");
  }

  const response = await fetch(API_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${OPENROUTER_API_KEY}`,
    },
    body: JSON.stringify({
      model: MODEL,
      messages: [{ role: "user", content: prompt }],
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    console.error("OpenRouter Error:", errorText);
    throw new Error(`Failed to fetch from AI model: ${errorText}`);
  }

  const data = await response.json();

  if (!data.choices || data.choices.length === 0) {
    console.error("No choices returned from AI:", data);
    throw new Error("No response text generated by AI model");
  }

  const text = data.choices[0].message.content;

  if (!text) {
    throw new Error("No text received from AI");
  }

  return text;
}

/**
 * The main Edge Function handler.
 * It processes incoming requests, handles CORS preflight, and manages the execution flow.
 *
 * @param {Request} req - The standard Web API Request object.
 * @returns {Promise<Response>} The standard Web API Response object.
 */
export default async function handler(req) {
  // Handle CORS preflight requests (OPTIONS)
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 200, headers: headers });
  }

  // Enforce POST method only
  if (req.method !== "POST") {
    return createJsonResponse({ error: "Method not allowed" }, 405);
  }

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader || !authHeader.startsWith("Bearer ")) {
      return createJsonResponse(
        { error: "Missing or invalid authorization header" },
        401
      );
    }

    const idToken = authHeader.split("Bearer ")[1];
    const isValid = await verifyFirebaseToken(idToken);
    if (!isValid) {
      return createJsonResponse({ error: "Unauthorized: Invalid token" }, 401);
    }

    // Parse and validate the incoming JSON body
    let prompt;
    try {
      const body = await req.json();
      prompt = body.prompt;
    } catch {
      return createJsonResponse({ error: "Invalid JSON body" }, 400);
    }

    if (!prompt) {
      return createJsonResponse({ error: "Prompt is required" }, 400);
    }

    const aiText = await fetchAIResponse(prompt);

    return createJsonResponse({ result: aiText }, 200);
  } catch (error) {
    console.error("Server Error:", error);
    const errorMessage =
      error instanceof Error ? error.message : "Internal server error";
    return createJsonResponse({ error: errorMessage }, 500);
  }
}
